### ISSUE TITLE
Cheats don't work

### ISSUE THREAD

**Issue by drguildo** [CruS-Modding-Infrastructure/crus-modbase#1] opened 2023-11-03 12:46 UTC
The cheat mode in this mod doesn't seem to work. I type in "ceomindset" and hit Enter, but I don't get the "Cheat prompt activated" notification the source code suggests I should get, and the key/keys I'm supposed to hit don't do anything. Also, as a related aside, the README is confusing as it suggests I should be pressing 3 keys after cheat mode is enabled ("`/~"). Is that correct? Or are you listing the symbols that might be on a particular key?

The logs indicate the mod is being loaded correctly:

```
-- CRUELTY SQUAD MOD LOADER v. 0.2.1 --

12:25:50 - [Mod Loader] Scanning mods folder...
12:25:50 - [Mod Loader] Scanning user://mods/CruS Mod Base
12:25:50 - [Mod Loader] ...found mod "CruS Mod Base" by "crustyrashky"
12:25:50 - [Mod Loader] Finished scanning for mods, loading mod data...
12:25:50 - [Mod Loader] ...loading "CruS Mod Base" (1/1)
12:25:50 - [Mod Loader] ...loaded user://mods/CruS Mod Base/mod.zip
12:25:50 - [Mod Loader] ...init script at res://MOD_CONTENT/CruS Mod Base/init.gd
12:25:51 - [Mod Loader] Finished loading data packs, running init scripts...
12:25:51 - [Mod Loader] ...initializing "CruS Mod Base" (1/1)
12:25:52 - [CruS Mod Base] No backup folder detected so this is probably the modbase's first start, backing up saves...
12:25:52 - [CruS Mod Base] Loading user levels...
12:25:52 - [CruS Mod Base] LEVEL LOADING COMPLETE: No levels were loaded!
12:25:52 - [Mod Loader] MOD LOADING COMPLETE: Successfully loaded 1 mod(s)
```

**Comment by BrassySheep09** [comment] 2024-01-21 23:55
same issue. I believe the problem is most likely due to the mod creator not having updated the mod since 2021.

**Comment by DX9T0** [comment] 2024-08-04 14:43
Thanks, fixed in [latest version](https://github.com/CruS-Modding-Infrastructure/crus-modbase/releases/tag/0.4.2)

**Closed as completed by DX9T0** 2024-08-04 14:43 UTC
